version: '3'

services:
  realsense-recorder:
    build: .
    volumes:
      - ./output:/app/output
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/video2:/dev/video2
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    privileged: true
